Call.Cloud.Mvc/Models/LoginVm/Login_User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Call.Cloud.Mvc.Models.LoginVm
{
    public class Login_User
    {
        public string pass { get; set; }
        public string user { get; set; }
        public string nombre_user { get; set; }
        public string parame_usuario { get; set; }
        public string parame_contra { get; set; }
    }

    //public class LogOnModel
    //{
    //    [Required]
    //    [Display(Name = "User name")]
    //    public string UserName { get; set; }

    //    [Required]
    //    [DataType(DataType.Password)]
    //    [Display(Name = "Password")]
    //    public string Password { get; set; }

    //    [Display(Name = "Remember me?")]
    //    public bool RememberMe { get; set; }
    //}

}

Call.Cloud.Mvc/Controllers/BusinessController.cs
using Call.Cloud.Logica;
using Call.Cloud.Modelo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Call.Cloud.Mvc.Controllers
{
    public class BusinessController : Controller
    {
        public async Task<JsonResult> ListarNegocios(Business objBusinessBE)
        {
            BusinessLogica oBusinessLogica = new BusinessLogica();
            var lstBusinessBE = await oBusinessLogica.NegocioListar(objBusinessBE);// (objBusinessBE);
            return Json(lstBusinessBE, JsonRequestBehavior.AllowGet);
        }
    }
}

Call.Cloud.Mvc/Controllers/Login_userController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Call.Cloud.Mvc.Models.LoginVm;
using Call.Cloud.Mvc.Models.Acount;
using System.Threading.Tasks;
using Call.Cloud.Mvc.App_Start.Extenciones;
using Call.Cloud.Mvc.Models.DashBoard;
using Call.Cloud.Mvc.Controllers.Shared;

namespace Call.Cloud.Mvc.Controllers
{
    //public class Login_userController : Controller
    public class Login_userController : ApplicationController<LogOnModel>
    {
        // GET: Login_user
        public ActionResult Login_user()
        {
            return View();
        }

        public ActionResult Principal()
        {
            LogOnModel sessionModel = GetLogOnSessionModel();
            if (sessionModel is null)
            {
                return RedirectToAction("Login_User");
            }
            else
            {
                Alertas alerta = new Alertas();
                var NumAlertas = alerta.NumeroAlertas();
                ViewBag.Message = NumAlertas;
                var NumNotificaciones = alerta.NumeroNotificaciones();
                ViewBag.NumNotificaciones = NumNotificaciones;
                return View();
            }
        }
   
        public JsonResult ListarAlertaJson()
        {
            Alertas alerta = new Alertas();
            List<Models.Alertas.AlertaModel> ls = new List<Models.Alertas.AlertaModel>();
            ls = alerta.ListaAlertas();
            return Json(ls, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ListarNotificacionJson()
        {
            Alertas alerta = new Alertas();
            List<Models.Alertas.AlertaModel> ls = new List<Models.Alertas.AlertaModel>();
            ls = alerta.ListaNotificaciones();
            return Json(ls, JsonRequestBehavior.AllowGet);
        }
        
        public ActionResult Mantenimiento()
        {
            return View();
        }


        public JsonResult Login_usuario001(LogOnModel filtro){
            try {

                ///if (ModelState.IsValid)
                //{
                /*Set model to session*/
                SetLogOnSessionModel(filtro);
                /*Shows the session*/
                LogOnModel sessionModel = GetLogOnSessionModel();
                //return RedirectToAction("Index", "Home");
                //}

                LOGIN lg = new LOGIN();
                var datos = lg.Login_usuario(filtro);

                return Json(datos, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex) {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        public async Task<JsonResult> grafica1(Elements filtro)
        {
            Dashboard lg = new Dashboard();
            var datos = await lg.grafica1(filtro);
            return Json(datos, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> Office_Year(Elements filtro)
        {
            Dashboard lg = new Dashboard();
            var datos = await lg.grafica2(filtro);
            return Json(datos, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> graficaCall(Elements filtro)
        {
            Dashboard lg = new Dashboard();
            var datos = await lg.grafica3(filtro);
            return Json(datos, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> graficaBusiness(Elements filtro)
        {
            Dashboard lg = new Dashboard();
            var datos = await lg.grafica4(filtro);
            return Json(datos, JsonRequestBehavior.AllowGet);
        }
        public ActionResult LogOff()
        {
            /*distroy current session and go to login page*/
            AbandonSession();
            return RedirectToAction("Login_user", "Login_user");
        }
    }
}

Call.Cloud.Mvc/Controllers/OfficeController.cs
using Call.Cloud.Logica;
using Call.Cloud.Modelo;
using Call.Cloud.Mvc.App_Start.Extenciones;
using Call.Cloud.Mvc.Models.ReportsVM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Call.Cloud.Mvc.Models.OfficeVM;

namespace Call.Cloud.Mvc.Controllers
{
    public class OfficeController : Controller
    {
        // GET: Office
        //public async Task<ActionResult> Index()
        //{
        //    return View(await CrearModelo1());
        //}


        public async Task<JsonResult> ListarOficinas(Office objOfficeBE)
        {
            OfficeLogica oOfficeLogica = new OfficeLogica();
            var lstOfficeBE = await oOfficeLogica.OficinaListar(objOfficeBE);
            return Json(lstOfficeBE, JsonRequestBehavior.AllowGet);
        }

        //private async Task<ListaOfficeVm> CrearModelo1(Office Item = null)
        //{
        //    OfficeLogica oOfficeLogica = new OfficeLogica();
        //    EnterpriseLogica le = new EnterpriseLogica();
        //    if (Item == null)
        //        Item = new Office();
        //    var listaOffice = await oOfficeLogica.Retrieve(Item);
        //    var enterprise = await le.Retrieve(null);

        //    return new ListaOfficeVm(Item, listaOffice, enterprise);
        //}
        
        //public async Task<ActionResult> Buscar(Office filtro)
        //{
        //    return View("Grid", await CrearModelo1(filtro));
        //}

        //[HttpGet]
        //public async Task<ActionResult> Editar(int id)
        //{
        //    OfficeLogica oSubOfficeLogica = new OfficeLogica();
        //    EnterpriseLogica oOfficeLogica = new EnterpriseLogica();

        //    var item = (id == -1) ? new Office() : await oSubOfficeLogica.Find(new Office
        //    {
        //        PkOffice = id
        //    });
        //    //??
        //    var listaBusiness = await oOfficeLogica.Retrieve(null);
        //    return View(new EditarOfficeVm(item, listaBusiness));
        //}

        //[HttpPost]

        //public async Task<ActionResult> Editar(Office Item)
        //{
        //    string mensajeRespuesta = "";
        //    OfficeLogica oSubOfficeLogica = new OfficeLogica();
        //    var rpta = await oSubOfficeLogica.Edit(Item);
        //    if (rpta == 2)
        //        mensajeRespuesta = "Se modificó correctamente el registro";
        //    else if (rpta == 1)
        //        mensajeRespuesta = "Se agregó correctamente el registro";
        //    else
        //        mensajeRespuesta = "Ocurrió un error";

        //    return RedirectToAction("Index", "Office", new { respuesta = mensajeRespuesta });

        //}

        //public async Task<ActionResult> Eliminar(int id)
        //{
        //    string mensajeRespuesta = "";
        //    OfficeLogica oSubOfficeLogica = new OfficeLogica();
        //    var rpta = await oSubOfficeLogica.Delete(new Office
        //    {
        //        PkOffice = id
        //    });

        //    if (rpta > 0)
        //        mensajeRespuesta = "Se eliminó correctamente el registro";
        //    else
        //        mensajeRespuesta = "Ocurrió un error";

        //    return RedirectToAction("Index", "Office", new { respuesta = mensajeRespuesta });

        //}

        //private async Task<ListaReportOffice> CrearModelo(ReportVmOffice Item = null)
        //{
        //    Enterprise Item1 = new Enterprise();
        //    Reporte rp = new Reporte();
        //    Reporte rl = new Reporte();
        //    EnterpriseLogica le = new EnterpriseLogica();
        //    if (Item == null)
        //        Item = new ReportVmOffice();
        //    var listaEnterprise = await le.Retrieve(Item1);
        //    var datos_enterprise = await rl.grafica01(Item);
        //    return new ListaReportOffice(Item, datos_enterprise, listaEnterprise);
        //}
    }
}

Call.Cloud.Mvc/Views/Login_user/Login_user.cshtml
@model Call.Cloud.Mvc.Models.LoginVm.ListarLoginVm
@{
    ViewBag.Title = "Login_user";
    //Layout = "~/Views/Shared/_Layout_Login.cshtml";
    Layout = "~/Views/Shared/_Login.cshtml";
}

<head>
    <link href="~/Content/Login/animate-custom.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/Login/demo.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/Login/style.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/Login/style2.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/Login/style3.css" type="text/css" rel="stylesheet" />
    @*<script src="~/Scripts/Calender/jquery-1.12.0.min.js"></script>*@
</head>


<form class="validate-login" novalidate>
    <div class="form-group">
        <label class="form-label" for="parame_usuario">Username</label>
        @Html.EditorFor(model => model.Filtro.parame_usuario, new
        {
            htmlAttributes = new
        {
                @class = "form-control",
                @placeholder = "Enter your user",
                @required = "required",
        @type = "text",
                @maxlength = "100"
            }
        })
        <span class="help-block">
            Usuario de acceso al aplicativo
        </span>
    </div>
    <div class="form-group">
        <label class="form-label" for="parame_contra">Password</label>
        @Html.EditorFor(model => model.Filtro.parame_contra, new
                {
                    htmlAttributes = new
                {
                        @class = "form-control",
                        @type = "password",
                        @required = "required",
                @placeholder = "Enter your password",
                        @maxlength = "100"
                    }
                })
        <span class="help-block">
            Password del aplicativo
        </span>
    </div>
    <div class="form-group text-left">
        <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" id="rememberme">
            <label class="custom-control-label" for="rememberme"> Remember me for the next 30 days</label>
        </div>
    </div>
    <button type="button" id="btnIngresar" onclick="Login01();" class="btn btn-default float-right">Secure login</button>
</form>

@*<div class="page animsition">
    <div class="panel-body">
        <div id="container_demo">
            <a class="hiddenanchor" id="toregister"></a>
            <a class="hiddenanchor" id="tologin"></a>
            <div id="wrapper">
                <div id="login" class="animate form">
                    <h1>LISTEN TO ME</h1>

                    <br />
                    <p>
                        @Html.Label("parame_usuario", "User: ", htmlAttributes: new { @class = "uname" })
                    @Html.EditorFor(model => model.Filtro.parame_usuario, new
                    {
                        htmlAttributes = new
                    {
                            @class = "form-control",
                            @placeholder = "Enter your user",
                            @required = "required",
                    @type = "text",
                            @maxlength = "100"
                        }
                    })
                </p>
                <p>
                    @Html.Label("parame_contra", "Password: ", htmlAttributes: new { @class = "youpasswd" })
                @Html.EditorFor(model => model.Filtro.parame_contra, new
                {
                    htmlAttributes = new
                {
                        @class = "form-control",
                        @type = "password",
                        @required = "required",
                @placeholder = "Enter your password",
                        @maxlength = "100"
                    }
                })
            </p>
            <p class="keeplogin">
                <input type="checkbox" name="loginkeeping" id="loginkeeping" value="loginkeeping" />
                <label for="loginkeeping">Remember Password</label>
            </p>
            <p class="text-center">
                <input type="submit" value="Ingresar" onclick="Login01();" />
            </p>
            <p class="change_link"></p>
        </div>
    </div>
</div>
</div>
<div id="pp">

</div>
</div>*@

<script type="text/javascript">

    $("#Filtro_parame_contra").on('keypress', function (e) {
        if (e.which === 13) {
            Login01();
        }
    });

    $("#Filtro_parame_usuario").on('keypress', function (e) {
        if (e.which === 13) {
            Login01();
        }
    });

    function Login01() {
        var parametros = {
            parame_usuario: $("#Filtro_parame_usuario").val(),
            parame_contra: $("#Filtro_parame_contra").val()
        };

        if (parametros.parame_usuario == "" && parametros.parame_contra == "") {
            //alert('Ingrese el Usuario');

            $("#login").addClass('animated bounce');
            $("#login").one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', function () {
                $(this).removeClass('animated bounce');
            });
        }

        else if ($("#Filtro_parame_usuario").val() == "") {
            //alert('Ingrese el Usuario');
            $("#Filtro_parame_usuario").addClass('animated shake');
            $("#Filtro_parame_usuario").one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', function () {
                $(this).removeClass("animated shake");
            });
        } else if ($("#Filtro_parame_contra").val() == "") {
            //alert('Ingrese contraseña');
            $("#Filtro_parame_contra").addClass('animated shake');
            $("#Filtro_parame_contra").one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', function () {
                $(this).removeClass('animated shake');
            });
        }

         else if (parametros.parame_usuario != "" && parametros.parame_contra != "") {

            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: '@Url.Action("Login_usuario001")',
                data: { filtro: parametros },
                success: function (data) {
                    for (var i = 0; i < data.length; i++) {
                        var array = new Array();
                        if (data[i].user != $("#Filtro_parame_usuario").val()) {
                            alert('Error de Usuario');
                        } else if (data[i].pass != $("#Filtro_parame_contra").val()) {
                            alert('Error de contraseña');
                        } else if (data[i].user == $("#Filtro_parame_usuario").val() && data[i].pass == $("#Filtro_parame_contra").val()) {
                            array = [data[i].nombre_user];
                            data[i].nombre_user = array[i];
                            var name = array;
                            var url = '@Url.Action("Principal","Login_user", new {name="hola"})';
                                url = url.replace("hola", name);
                                location.href = url;
                            @*window.setTimeout(function () {
                                var url = '@Url.Action("Principal","Login_user", new {name="hola"})';
                                url = url.replace("hola", name);
                                location.href = url;
                            }, 100);*@
                        }
                    }
                }

            });
        }
        return false;
    }

</script>
<script>
    function pasarVariables(pagina, nombres) {
        pagina += "?";
        nomVec = nombres.split(",");
        for (i = 0; i < nomVec.length; i++)
            pagina += nomVec[i] + "=" + escape(eval(nomVec[i])) + "&";
        pagina = pagina.substring(0, pagina.length - 1);
        location.href = pagina;
    }
</script>

Call.Cloud.Mvc/Views/Login_user/Mantenimiento.cshtml
@model Call.Cloud.Mvc.Models.DashBoard.Elements
@{
    ViewBag.Title = "Mantenimiento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{ 
    <head>

    </head>
}

<div class="panel-body">
    <br /><br />
    <div class="col-sm-12"> 
        <div class="col-sm-4">
            <div style="width:400px; height:250px; text-align:center">                            
                <button type="button" class="btn-lg btn-default disabled" style="width:100px; height:75px;">
                    <img src="~/Content/images/adminis.gif" style="width:50px; height:50px;" />
                </button>
                <h5 style="font-family:'Times New Roman'">ENTERPRISE</h5>
            </div>
        </div>
        <div class="col-sm-4">
            <div style="width:400px; height:250px; text-align:center">
                <button type="button" class="btn-lg btn-default active"  onclick="window.location = '@Url.Action("Index","Office")';" style="width:100px; height:75px;">
                    <img src="~/Content/images/ejecutivos-01.gif" style="width:80px; height:50px;" />
                </button>
                <h5 style="font-family:'Times New Roman'">OFFICE</h5>
            </div>
        </div>
        <div class="col-sm-4">
            <div style="width:400px; height:250px; text-align:center">
                <button type="button" class="btn-lg btn-default active" style="width:100px; height:75px;"> @*onclick="window.location = '@Url.Action("Index","SubOffice")';" *@
                    <img src="~/Content/images/ka61ia.jpg" style="width:50px; height:50px;" />
                </button>
                <h5 style="font-family:'Times New Roman'">SUBOFFICE</h5>
            </div>
        </div>
    </div>           

    <div class="col-sm-12">
        <br />
        <div class="col-sm-4">
            <div style="width:400px; height:250px; text-align:center" >
                @*onclick="window.location = '@Url.Action("Index","Business")';"*@
                <button type="button" class="btn-lg btn-default active"   style="width:100px; height:75px;">
                    <img src="~/Content/images/servicios-internet-2-296x300.jpg" style="width:60px; height:50px;" />     
                </button>
                <h5 style="font-family:'Times New Roman'">BUSINESS</h5>              
            </div>
        </div>
        <div class="col-sm-4">
            <div style="width:400px; height:250px; text-align:center">
                <button type="button" class="btn-lg btn-default active" onclick="window.location = '@Url.Action("Index","Speech")';" style="width:100px; height:75px;">
                    <img src="~/Content/images/rapport-5101.gif" style="width:60px; height:50px;"/>
                </button>
                <h5 style="font-family:'Times New Roman'">SPEECH</h5>
            </div>
        </div>
        <div class="col-sm-4">
            <div style="width:400px; height:250px; text-align:center">
                <button type="button" class="btn-lg btn-default active"  onclick="window.location = '@Url.Action("Index","Agent")';" style="width:100px; height:75px;">
                    <img src="~/Content/images/b38080d5c31b648565f90bf9e789718f_90x90.gif" style="width:50px; height:50px;" />
                </button>
                <h5 style="font-family:'Times New Roman'">STAFF</h5>
            </div>
        </div>
    </div>

</div>