Call.Cloud.Mvc/Controllers/SectionController.cs
using Call.Cloud.Logica;
using Call.Cloud.Modelo;
using Call.Cloud.Mvc.Models.SectionVM;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Call.Cloud.Mvc.Controllers
{
    public class SectionController : Controller
    {
        #region Mantenimiento
        //public async Task<ActionResult> Index(string respuesta = "", int id = 0)
        //{
        //    ViewBag.Mensaje = respuesta;
        //    return View(await CrearModelo(new Section()
        //    {
        //        PkSpeech = id
        //    }));
        //}
        //private async Task<ListaSectionVm> CrearModelo(Section Item = null)
        //{
        //    SpeechLogica oSpeechLogica = new SpeechLogica();
        //    SectionLogica oSectionLogica = new SectionLogica();
        //    if (Item == null)
        //        Item = new Section();
        //    var listaSection = await oSectionLogica.Retrieve(Item);
        //    var listaSpeech = await oSpeechLogica.Retrieve(new Speech());

        //    return new ListaSectionVm(Item, listaSection, listaSpeech);
        //}

        
        //public async Task<ActionResult> Buscar(Section filtro)
        //{
        //    return View("Grid", await CrearModelo(filtro));
        //}
        //[HttpGet]
        //public async Task<ActionResult> Editar(int id)
        //{
        //    SectionLogica oSectionLogica = new SectionLogica();
        //    SpeechLogica oSpeechLogica = new SpeechLogica();
        //    var item = (id == -1) ? new Section() : await oSectionLogica.Find(new Section
        //    {
        //        PkSection = id
        //    });
        //    var listaSpeech = await oSpeechLogica.Retrieve(new Speech());
        //    return View(new EditarSectionVm(item, listaSpeech));
        //}

        //[HttpPost]
        //public async Task<ActionResult> Editar(Section Item)
        //{
        //    string mensajeRespuesta = "";
        //    SectionLogica oRuleLogica = new SectionLogica();
        //    var rpta = await oRuleLogica.Edit(Item);
        //    if (rpta == 2)
        //        mensajeRespuesta = "Se modificó correctamente el registro";
        //    else if (rpta == 1)
        //        mensajeRespuesta = "Se agregó correctamente el registro";
        //    else
        //        mensajeRespuesta = "Ocurrió un error";

        //    return RedirectToAction("Index", "Section");
        //}

        ////*******************Agregar una Section dentro de un Speech********************
        //[HttpGet]
        //public async Task<ActionResult> EditarBySpeech(int id, string namespeech, int speech)
        //{
        //    Session["PkSpeech"] = speech;
        //    Session["PkSection"] = id;
        //    Session["SpeechName"] = namespeech;

        //    SectionLogica oSectionLogica = new SectionLogica();
        //    SpeechLogica oSpeechLogica = new SpeechLogica();

        //    var listaSpeech = await oSpeechLogica.Retrieve(new Speech());

        //    var item = (id == -1) ? new Section
        //    {
        //        PkSpeech = speech
        //    } : await oSectionLogica.Find(new Section
        //    {
        //        PkSection = id,
        //        PkSpeech = speech
        //    });

        //    return View(new EditarSectionVm(item, listaSpeech));
        //}


        //[HttpPost]
        //public async Task<ActionResult> EditarBySpeech(Section Item)
        //{
        //    int speech = (int)Session["PkSpeech"];
        //    string namespeech = (string)Session["SpeechName"];
        //    int sec = (int)Session["PkSection"];

        //    bool estado = Item.Status;
        //    Session["Estado"] = estado;

        //    string mensajeRespuesta = "";
        //    SectionLogica oRuleLogica = new SectionLogica();
        //    var rpta = await oRuleLogica.Edit(Item);
        //    if (rpta == 2)
        //        mensajeRespuesta = "Se modificó correctamente el registro";
        //    else if (rpta == 1)
        //        mensajeRespuesta = "Se agregó correctamente el registro";
        //    else
        //        mensajeRespuesta = "Ocurrió un error";

        //    return RedirectToAction("SectionBySpeech/" + speech, "Speech", new {section=sec, name=namespeech });
        //}

        ////******************************************************************************

        //public async Task<ActionResult> Eliminar(int id)
        //{

        //    string mensajeRespuesta = "";
        //    SectionLogica oRuleLogica = new SectionLogica();
        //    var rpta = await oRuleLogica.Delete(new Section
        //    {
        //        PkSection = id
        //    });

        //    if (rpta > 0)
        //        mensajeRespuesta = "Se eliminó correctamente el registro";
        //    else
        //        mensajeRespuesta = "Ocurrió un error";

        //    return RedirectToAction("Index", "Section");

        //}
        #endregion
        //public async Task<ActionResult> EliminarSection(int id, int speech)
        //{

        //    string mensajeRespuesta = "";
        //    SectionLogica oSectionLogica = new SectionLogica();

        //    ViewBag.pkSpeech = speech;

        //    var rpta = await oSectionLogica.Delete(new Section
        //    {
        //        PkSection = id
        //    });

        //    if (rpta > 0)
        //        mensajeRespuesta = "Se eliminó correctamente el registro";
        //    else
        //        mensajeRespuesta = "Ocurrió un error";

        //    return RedirectToAction("SectionBySpeech/" + speech, "Speech", new { pkSpeech=speech });

        //}

        
        //public async Task<ActionResult> WordRuleBySection(int id, string name, int speech, string namespeech)
        //{

        //    return PartialView("WordRuleBySection", await creacion(id,name,speech, namespeech)); //vista parcial 
        //                                                                                  //que me trae las "Reglas" y "Palabras Reglas"
        //}

        //public async Task<ListaWordRuleSectionVm> creacion(int id, string name, int speech, string namespeech="")
        //    //captura el pkSection, sectionName, pkSpeech, speechName dando click al botón "Listar"
        //{
        //    SectionLogica section = new SectionLogica();
        //    WordRuleLogica logica = new WordRuleLogica();

        //    Session["SectionName"] = name;
        //    Session["PkSection"] = id;
        //    Session["pkSpeech"] = speech;
        //    Session["SpeechName"] = namespeech;
            
        //    var filtro = await logica.Find(new WordRule());
        //    var reglas = await section.RetrieveSectionRuleWordRule(id);//trae las reglas --> vista: WordRuleBySection que está dentro de la vista "SectionBySpeech"
        //    var WordRuleLista = await logica.ListarWordRule(id);//trae las palabras reglas --> vista: GridWordRule que está dentro de la vista "WordRuleBySection"
         
        //    return new ListaWordRuleSectionVm(filtro, WordRuleLista, reglas);
        //}
        
        
    }
}

Call.Cloud.Mvc/Controllers/SpeechController.cs
using Call.Cloud.Logica;
using Call.Cloud.Modelo;
using Call.Cloud.Mvc.Models.SpeechVM;
using System.Threading.Tasks;
using System.Web.Mvc;

/* Seguridad */
using Call.Cloud.Mvc.Models.Acount;
using Call.Cloud.Mvc.Controllers.Shared;
/* Fin Seguridad */

namespace Call.Cloud.Mvc.Controllers
{
    public class SpeechController : ApplicationController<LogOnModel>
    {
        #region Mantenimiento
        public async Task<ActionResult> Index(string respuesta = "")
        {
            LogOnModel sessionModel = GetLogOnSessionModel();
            if (sessionModel is null)
            {
                return RedirectToAction("Login_User");
            }
            else
            {
                ViewBag.Mensaje = respuesta;
                return View(await CrearModelo());
            }
                
        }

        private async Task<ListaSpeechVm> CrearModelo(Speech Item = null)
        {
            Section section = new Section();
            SpeechLogica OSpeechLogica = new SpeechLogica();
            SectionLogica OSectionLogica = new SectionLogica();
            
            BusinessLogica oBusinessLogica = new BusinessLogica();
            if (Item == null)
                Item = new Speech();
            
            var listaSpeech = await OSpeechLogica.Retrieve(Item);
            Business oBusiness = new Business();
            var listaBussines = await oBusinessLogica.Retrieve(oBusiness);
            var listaSecciones = await OSectionLogica.Retrieve(section);
            return new ListaSpeechVm(Item, listaSpeech, listaBussines,listaSecciones);
        }

        
        public async Task<ActionResult> Buscar(Speech filtro)
        {
            return View("Grid", await CrearModelo(filtro));
        }

        //[HttpGet]
        //public async Task<ActionResult> Editar(int id)
        //{
        //    SpeechLogica OSpeechLogica = new SpeechLogica();
        //    BusinessLogica oBusinessLogica = new BusinessLogica();
        //    var item = (id == -1) ? new Speech() : await OSpeechLogica.Find(new Speech
        //    {
        //        PkSpeech = id
        //    });
        //    Business oBusiness = new Business();
        //    var listaSubOffice = await oBusinessLogica.Retrieve(oBusiness);
        //    return View(new EditarSpeechVm(item, listaSubOffice));
        //}

        [HttpPost]
        public async Task<ActionResult> Editar(Speech Item)
        {
#pragma warning disable CS0219 // The variable 'mensajeRespuesta' is assigned but its value is never used
            string mensajeRespuesta = "";
#pragma warning restore CS0219 // The variable 'mensajeRespuesta' is assigned but its value is never used
            SpeechLogica OSpeechLogica = new SpeechLogica();
            var rpta = await OSpeechLogica.Edit(Item);
            if (rpta == 2)
                mensajeRespuesta = "Se modificó correctamente el registro";
            else if (rpta == 1)
                mensajeRespuesta = "Se agregó correctamente el registro";
            else
                mensajeRespuesta = "Ocurrió un error";

            return RedirectToAction("Index", "Speech");
        }

        //public async Task<ActionResult> Eliminar(int id)
        //{
        //    string mensajeRespuesta = "";
        //    SpeechLogica OSpeechLogica = new SpeechLogica();
        //    var rpta = await OSpeechLogica.Delete(new Speech
        //    {
        //        PkSpeech = id
        //    });

        //    if (rpta > 0)
        //        mensajeRespuesta = "Se eliminó correctamente el registro";
        //    else
        //        mensajeRespuesta = "Ocurrió un error";
        //    return RedirectToAction("Index", "Speech");
        //}
        #endregion

        //public async Task<ActionResult> SectionBySpeech(int id, string name="", string sectionname="", int PkSection=0)
        //{
        //    LogOnModel sessionModel = GetLogOnSessionModel();
        //    if (sessionModel is null)
        //    {
        //        return RedirectToAction("Login_User");
        //    }
        //    else
        //    {
        //        SpeechLogica oSpeechLogica = new SpeechLogica();

        //        Session["PkSpeech"] = id;
        //        Session["SpeechName"] = name;
        //        Session["SectionName"] = "";
        //        Session["PkSection"] = PkSection;
        //        ViewBag.Section = PkSection;
        //        ViewBag.nombreSection = sectionname;
        //        ViewBag.nombrespeech = name;

        //        var listaSecciones = await oSpeechLogica.RetrieveSectionSpeech(id);
        //        return View("SectionBySpeech", listaSecciones);
        //    }
        //}
        public async Task<JsonResult> ListarSpeech(Speech objSpeechBE)
        {
            SpeechLogica oSpeechLogica = new SpeechLogica();
            var lstSpeechBE = await oSpeechLogica.SpeechListar(objSpeechBE);// Retrieve(objSpeechBE);
            return Json(lstSpeechBE, JsonRequestBehavior.AllowGet);
        }
    }
}

Call.Cloud.Mvc/Views/Speech/Editar.cshtml
@model Call.Cloud.Mvc.Models.SpeechVM.EditarSpeechVm
@{
    ViewBag.Title = "Speech";
    Layout = "";
}
<div class="col-sm-12">
    <div>
        @using (@Html.BeginForm("Editar", "Speech", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.Item.PkSpeech)

            int pk = Int32.Parse(Model.Item.PkSpeech.ToString());
            Session["SessionSpeechName"] = pk;

            <div class="form-group">
                @Html.Label("Business", "Business", htmlAttributes: new { @class = "form-label" })
                @Html.DropDownListFor(model => model.Item.PK_Business, Model.Business, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.Label("LastName", "Name", htmlAttributes: new { @class = "form-label" })
                @Html.EditorFor(model => model.Item.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Name", @maxlength = "350", @onkeypress = "return soloLetras(event)", @onpaste = "return false" } })
            </div>
            <div class="form-group">
                @Html.Label("Description", "Description", htmlAttributes: new { @class = "form-label" })
                <br />
                @Html.TextAreaFor(model => model.Item.Description, new
                {
                    style = "width:100%;height: 50px",
                    htmlAttributes = new
                {
                        @class = "form-control",
                        @placeholder = "Description",
                        @maxlength = "2000",
                        @onkeypress = "return soloLetras(event)",
                    @onpaste = "return false"
                    }
                })
            </div>
            <div class="form-group">
                <div>
                    <button type="submit" class="btn btn-primary" onclick="return grabar();">Save</button>
                    <button type="button" class="btn btn-warning" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        }
    </div>
</div>

Call.Cloud.Mvc/Views/Speech/Grid.cshtml
@model Call.Cloud.Mvc.Models.SpeechVM.ListaSpeechVm
@{
    ViewBag.Title = "Grid";
    Layout = "";
}

<div class="page animsition" style="animation-duration: 800ms; opacity: 1;">
    <div class="panel-body">
        <div id="divGridPagina" class="table-responsive">
            @Html.Hidden("items_count", Model.Elementos.Count())
            <table class="table table-striped table-condensed text-center">
                <tr>
                    <th>
                        <a class="punteroMouse">Name</a>
                    </th>
                    <th>
                        <a class="punteroMouse">Description</a>
                    </th>
                    <th>
                        <a class="punteroMouse">Business</a>
                    </th>
                    <th>Option</th>
                </tr>

                @for (var i = 0; i < Model.Elementos.Count(); i++)
                {
                    var item = Model.Elementos.ToList()[i];
                    <tr>
                        <td style="text-align: justify;" class="text-center">@item.SpeechName</td>
                        <td style="text-align: justify;">@item.Description</td>
                        <td class="text-center">@item.nameBusiness</td>
                        <td class="text-right">
                            <a class="btn btn-sm btn-icon btn-primary btn-round" title="Editar" data-toggle="modal" data-original-title="Editar" 
                               data-target="#ModalSpeech" data-id="@item.PkSpeech">
                                <i class="fal fa-edit" aria-hidden="true"></i>
                            </a>
                            <a class="btn btn-sm btn-icon btn-primary btn-round" title="Eliminar" onclick="eliminar('@item.PkSpeech')" data-toggle="tooltip"
                               data-original-title="Eliminar">
                                <i class="fal fa-eraser" aria-hidden="true"></i>
                            </a>
                            @Html.ActionLink(" ", "SectionBySpeech", new { id = item.PkSpeech, name = item.SpeechName, estado=item.Status }, new { @class = "icon wb-list" })
                        </td>
                        @{ 
                            Session["SpeechName"] = item.SpeechName;
                            Session["Estado"] = item.Status;

                        }
                    </tr>
                }

            </table>
        </div>
    </div>
</div>

Call.Cloud.Mvc/Views/Speech/SectionBySpeech.cshtml
@model  IEnumerable<Call.Cloud.Modelo.Speech>
@{
    ViewBag.Title = "SPEECH";
    Layout = "~/Views/Shared/_Layout.cshtml";

    string nom = string.Empty;

    string name2 = "";

    name2 = (String)Session["SpeechName"];

    string seccion = (string)Session["SectionName"];

    int pkspeech = 0;
    pkspeech = (int)Session["PkSpeech"];

    int pksection = 0;
    pksection = (int)Session["PkSection"];

    bool status = false;
    status = (bool)Session["Estado"];

}
<head>
    <script type="text/javascript" src="~/Scripts/usados/wordRuleBySection.js"></script>
    @{

        <script type="text/javascript">
            debugger;
            var section = section || {};
            section.Urls = section.Urls || {};
            section.Urls.baseUrl = '@Url.Content("~")';
            section.Urls.editarSectionUrl = '@Url.Action("EditarBySpeech", "Section")';
            section.Urls.listarReglasWordUrl = '@Url.Action("WordRuleBySection", "Section")';
            section.Urls.deleteSectionUrl = '@Url.Action("EliminarSection", "Section")';
            section.Urls.cargarSectionUrl = '@Url.Action("SectionBySpeech", "Speech")';
        </script>


    }

</head>

<div class="page animsition">
    <div class="page-header">
        <h1 class="page-title">@ViewBag.Title</h1>
        <br />
        <div class="panel panel-heading">
            <div class="panel-body form-horizontal">

                <div class="text-center col-sm-6">

                    <h4>Speech :  @name2 </h4>

                    <!--Botón agregar nueva Sección-->
                    <div class="text-right">
                        <button type="button" class="btn btn-sm btn-icon btn-primary btn-round" data-toggle="modal"
                                data-original-title="Nuevo" title="Nuevo" data-target="#ModalSection" data-id="-1"
                                data-namespeech="@name2" data-speech="@pkspeech">
                            <i class="icon md-sign-in" aria-hidden="true"></i>
                        </button>
                    </div>
                    <!--   -->
                    <!-- *************************  Inicia el form **************************** -->
                    <form id="formAusenciaFiltro" role="form">
                        @for (int i = 0; i < Model.ToList().Count(); i++)
                        {

                            <div class="form-group">
                                <div class="text-left">
                                    <h5>
                                        Section :
                                        @Html.Label("Item.FirstName", Model.ToList()[i].SectionName, htmlAttributes: new { @class = "control-label" })
                                    </h5>

                                </div>

                                <div class="col-sm-12 inline-block" style="padding-bottom: 5px;">
                                    <div class="text-left col-sm-2">
                                        @Html.Label("Item.Weight", "Peso", htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="text-right col-sm-4">
                                        @Html.TextBox("Weight", Model.ToList()[i].WeightSection, htmlAttributes: new { @class = "form-control round text-right", @disabled = "disabled" })
                                    </div>
                                    <div class="text-right col-sm-2">
                                        @Html.Label("Item.TMO", "TMO", htmlAttributes: new { @class = "control-label" })
                                    </div>
                                    <div class="text-right col-sm-4">
                                        @Html.TextBox("TMO", Model.ToList()[i].TMO, htmlAttributes: new { @class = "form-control round text-right", @disabled = "disabled" })
                                    </div>
                                </div>
                                <br /> <br />
                                <div class="text-center col-sm-12">
                                    <a class="btn btn-sm btn-icon btn-primary btn-round" title="Editar" data-toggle="modal" data-original-title="Editar"
                                       data-target="#ModalSection" data-id="@Model.ToList()[i].PkSection" data-namespeech="@Model.ToList()[i].SpeechName" data-speech="@Model.ToList()[i].PkSpeech">
                                        <i class="icon md-edit" aria-hidden="true"></i>
                                    </a>

                                    <a class="btn btn-sm btn-icon btn-primary btn-round" title="Eliminar" onclick="eliminarSection('@Model.ToList()[i].PkSection',
                                       '@pkspeech')"
                                       data-toggle="tooltip" data-original-title="Eliminar">
                                        <i class="icon md-delete" aria-hidden="true"></i>
                                    </a>

                                    <a class="btn btn-sm btn-icon btn-primary btn-round" title="Listar" data-original-title="listar" id="@Model.ToList()[i].PkSection"
                                       onclick="listar('@Model.ToList()[i].PkSection', '@Model.ToList()[i].SectionName', '@Model.ToList()[i].PkSpeech','@Model.ToList()[i].SpeechName')" data-toggle="tooltip">
                                        <i class="icon md-long-arrow-tab" aria-hidden="true"></i>
                                        @{
                                            Session["Status"] = Model.ToList()[i].Status;
                                            Session["NombreSeccion"] = Model.ToList()[i].SectionName;
                                        }
                                    </a>
                                </div>
                                <br /> <br />

                                <!--esto es la sección completa, la descripción-->
                                @foreach (var des in Model.ToList()[i].descripcion)
                                {
                                    nom += des + "";
                                }
                                @Html.TextAreaFor(model => nom, new { @class = "form-control", @placeholder = "Description", @maxlength = "500", @readonly = "readonly" })
                                @{
                                    nom = string.Empty;
                                }

                            </div><br />

                        }

                    </form>

                </div>
                <!--Empiezan las reglas-->
                <div class="col-sm-6">
                    <div id="divGrid" class="col-sm-12">
                        @Html.Hidden("GridRule")
                    </div>
                </div>

                <!--Empieza el pie-->
                <form>
                    <div class="col-sm-12">
                        <br /><br /><br />
                        <div class="text-center">
                            @Html.ActionLink("Return", "Index", "Speech", htmlAttributes: new { @class = "btn btn-default" })
                            <button id="btnBuscar" class="btn btn-primary" type="button" onclick="">Buscar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div><!--fin de todo-->
    </div>
</div>
<div class="modal fade modal-3d-slit" id="ModalSection" aria-hidden="true"
     aria-labelledby="exampleModalTitle" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Sections</h4>
            </div>
            <div class="modal-body" id="divModalSection">
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        function listar(id, name, speech, namespeech) {

            var urlListarReglas = section.Urls.listarReglasWordUrl;

            if (id > 0)
                $.ajax({

                    url: urlListarReglas,
                    data: {
                        id: id,
                        name: name,
                        speech: speech,
                        namespeech: namespeech
                    },
                    Type: 'GET'
                }).done(function (data, textStatus, jqXhr) {

                    $("#divGrid").html(data);

                }).fail(function (data, textStatus, jqXhr) {

                    console.log(data);
                });
            return false;

        };
    </script>

    <script>
    (function () {
        var section =@ViewBag.Section;
        $("#"+section).click();

        var nombre="@ViewBag.nombreSection";
        $("#"+nombre).click();
        debugger;

        var name="@ViewBag.nombrespeech";
        $("#"+name).click();
        debugger;

        var estado= '@Session["Status"]';
        debugger;

        if ("@status" == estado) {

            if ("@pksection" == "@pksection") {
                debugger;
                iniciarSection();
                listar("@pksection", nombre, "@pkspeech", "@name2");
            }
        }
        else {
            debugger;
            iniciarSection();
        }

    })();

    function eliminarSection(id, speech) {

        var urlEliminarSection = section.Urls.deleteSectionUrl;
        var retornar = section.Urls.cargarSectionUrl;

        var section =@ViewBag.Section;
        $("#"+section).click();

        var nombre="@ViewBag.nombreSection";
        $("#"+nombre).click();
        debugger;

        debugger;

        if (confirm("¿Está seguro de Eliminar esta Sección?")) {
            if (id > 0)
                $.ajax({
                    url: urlEliminarSection,
                    data: {
                        id: id,
                        speech: speech
                    },
                    type: 'GET'
                }).done(function (data, textStatus, jqXhr) {
                    debugger;
                    window.location.href =retornar;
                }).fail(function (data, textStatus, jqXhr) {
                    debugger;
                    console.log(data);
                });

            return false;

        }
    }
    </script>
}